<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>91c72c92-c197-41b2-b10f-47d0006a0415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/section/div[4]/div/div/div[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d597db23-a504-4794-887d-35d085e8bdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://binmile.com/wp-content/uploads/2023/03/trepp-small-logo.png</value>
      <webElementGuid>3a048473-0f04-4e10-b46f-3c9b3974e264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>52e573ad-ebf1-425e-9da3-92eb9cfd9780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>889d5c44-73bb-4811-999e-be83b3eeff9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Trepp Logo</value>
      <webElementGuid>8b1bb674-3595-4926-a8a6-2ae708b7a15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://binmile.com/wp-content/uploads/2023/03/trepp-small-logo.png</value>
      <webElementGuid>fc09d0cc-eaf4-4bc1-b00f-352f084a790b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>38ad8aed-cdb7-4e16-9756-a0e9e725cce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entered lazyloaded</value>
      <webElementGuid>a8021706-9e44-4f58-8b5f-9069a79a7c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/section[@class=&quot;home-video-bg hero-section&quot;]/div[@class=&quot;slider-thumb owl-carousel owl-theme owl-loaded owl-drag&quot;]/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item active&quot;]/div[@class=&quot;item&quot;]/div[@class=&quot;client-logo&quot;]/img[@class=&quot;entered lazyloaded&quot;]</value>
      <webElementGuid>419d8d36-f6d4-4ecd-81c4-dcdd5891ef6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/section/div[4]/div/div/div[4]/div/div/img</value>
      <webElementGuid>e397657a-d885-467f-8545-9e7f79d7e5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Trepp Logo']</value>
      <webElementGuid>c5f48c3c-93fc-4693-a021-8e7284b26a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/img</value>
      <webElementGuid>b7bc7721-5ad6-4a97-9752-9c8cc951e7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://binmile.com/wp-content/uploads/2023/03/trepp-small-logo.png' and @alt = 'Trepp Logo']</value>
      <webElementGuid>bf627640-ebd9-4324-8240-9d083b3e4681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
