<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_btnI</name>
   <tag></tag>
   <elementGuidId>eadf42b5-98e1-497c-b205-9db8c7b44970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.FPdoLc.lJ9FBc > center > input[name=&quot;btnI&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='btnI'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca1d1b2e-5c50-460f-8937-6773f9e4b54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RNmpXc</value>
      <webElementGuid>86b4e734-d67f-4cbe-9885-3a4f16ce2ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I'm Feeling Lucky</value>
      <webElementGuid>bda7d7b6-e622-4862-a268-0cb8d12f47cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>I'm Feeling Lucky</value>
      <webElementGuid>1cba2e48-c1a3-4356-bbbe-f2d64b4aabc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnI</value>
      <webElementGuid>d1d5987b-1cd5-4dc6-8195-bfdc91f3e499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>13fe9de4-7051-42b6-ac52-8ac68eda4146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>trigger.kWlxhc</value>
      <webElementGuid>2790a2b3-2934-453f-a5d0-d96db4d1f043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>0ahUKEwj6i97S0aeCAxWjr1YBHewpAvcQ19QECBA</value>
      <webElementGuid>06a016dc-8c6c-4dc7-84b3-06d3d8b10eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf&quot;]/div[@class=&quot;FPdoLc lJ9FBc&quot;]/center[1]/input[@class=&quot;RNmpXc&quot;]</value>
      <webElementGuid>ea65649f-c270-4c23-9d7d-4d036809aae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='btnI'])[2]</value>
      <webElementGuid>02be4718-1a18-441c-96e6-1aa201eb4a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/center/input[2]</value>
      <webElementGuid>2eae206c-54df-4b50-aa89-e5ff7abd4ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnI' and @type = 'submit']</value>
      <webElementGuid>817791c6-82bc-4f65-b66e-65bb5a6b0b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
