<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>c27a341a-497f-4255-89a4-f61e3944b5f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-info.alert-info-manual.alert-dismissible.bg-blue-40.border.border-blue-30.text-blue-60.relative.rounded.mb-15.pt-8.pb-8.pl-8.pr-100.font-medium > a.close.absolute.text-size-26.top-0.right-0.w-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section[3]/div/div/div/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26b3a955-d29c-46e9-af65-c8cce644f4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a0ac78e4-89a2-4a0b-9990-67fb951ae360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close absolute text-size-26 top-0 right-0 w-50</value>
      <webElementGuid>d194d1b5-5503-433e-8326-57f580d276c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>d9b469b4-fa29-4b93-adc6-f5b8ceb93c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>4e5f1c19-7f26-4795-ab00-c84d380a63d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>4fffb6d7-7286-433a-ba8f-e706e489936b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-full px-15&quot;]/div[@class=&quot;flex mt-20&quot;]/div[@class=&quot;w-6/12 px-15&quot;]/div[@class=&quot;alert alert-info alert-info-manual alert-dismissible bg-blue-40 border border-blue-30 text-blue-60 relative rounded mb-15 pt-8 pb-8 pl-8 pr-100 font-medium&quot;]/a[@class=&quot;close absolute text-size-26 top-0 right-0 w-50&quot;]</value>
      <webElementGuid>d6b170af-9b61-4e5a-a183-43e755b7aa15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>b0842d1c-c05f-46ca-b4bb-e304043090c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'×')])[2]</value>
      <webElementGuid>ed24aeac-bd9f-4c3d-8654-09adaf3a761f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autocloseable warning message. I will hide in 5 seconds.'])[1]/preceding::a[1]</value>
      <webElementGuid>74f23043-f685-4c0f-9b14-db0d9417f276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>7227c21a-b120-45c7-b03a-c0b5e3c4eb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>8e840e32-8f23-46c2-a1c0-567574d795d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '×' or . = '×')]</value>
      <webElementGuid>f7fd4961-1e49-4793-9e31-1d9ad6d730b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
