<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Checkbox Demo</name>
   <tag></tag>
   <elementGuidId>87f65ef5-bd04-425e-8108-3f9772fc1cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[2]/div/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44ed01c3-c910-4b3f-a036-6b4c91fba7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.lambdatest.com/selenium-playground/checkbox-demo</value>
      <webElementGuid>f4d2e386-6ab6-46e3-9f2c-1e80fb2ad7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black text-size-14 hover:text-lambda-900 leading-relaxed</value>
      <webElementGuid>6ff124b2-8513-4584-aaa8-af5ee0a3fcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkbox Demo</value>
      <webElementGuid>d19b29d0-7032-46fe-8a13-10a952ecf736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wrapper&quot;]/section[@class=&quot;mb-50&quot;]/div[@class=&quot;container__selenium&quot;]/ul[@class=&quot;list-disc pl-10 pb-30 grid grid-cols-4 w-full gap-10 mt-30 smtablet:grid-cols-1&quot;]/li[@class=&quot;pt-10&quot;]/a[@class=&quot;text-black text-size-14 hover:text-lambda-900 leading-relaxed&quot;]</value>
      <webElementGuid>f731f907-e73a-4b06-b67e-2d58258be72d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/ul/li[9]/a</value>
      <webElementGuid>26db521c-afc1-4277-b959-fbd7ea2375c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Checkbox Demo')]</value>
      <webElementGuid>b9cad80e-770d-479b-a87a-da2de6eced75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken Image'])[1]/following::a[1]</value>
      <webElementGuid>2e85a6c3-0397-4c2a-a3a9-9f34552e882b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bootstrap Progress bar'])[1]/following::a[2]</value>
      <webElementGuid>54b7b8da-b454-4131-b6e0-3bbfdc7fbd68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Context Menu'])[1]/preceding::a[1]</value>
      <webElementGuid>a03c57dc-d283-4138-9f59-b2dfe4e5a878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data List Filter'])[1]/preceding::a[2]</value>
      <webElementGuid>d2d9a7d3-2cf4-4aa9-883d-d1478b35847d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkbox Demo']/parent::*</value>
      <webElementGuid>51503480-8f77-4b32-b4ef-1131d6bb56db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.lambdatest.com/selenium-playground/checkbox-demo')]</value>
      <webElementGuid>f3c3d59a-1501-423d-a163-1ab6a4724988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/ul/li[9]/a</value>
      <webElementGuid>6fdfc02a-1d20-4f2e-a2f4-b0ec9ca7c933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.lambdatest.com/selenium-playground/checkbox-demo' and (text() = 'Checkbox Demo' or . = 'Checkbox Demo')]</value>
      <webElementGuid>65df58b1-d192-4bf6-8991-d9a89a904827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
