<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Radio Buttons Demo</name>
   <tag></tag>
   <elementGuidId>326ce618-b989-4dff-80b5-68281a33dc02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[2]/div/ul/li[30]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9a92b40-9d39-4f41-aa4f-91c923650700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.lambdatest.com/selenium-playground/radiobutton-demo</value>
      <webElementGuid>2862e700-3593-4c27-946c-9edd83ef4227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black text-size-14 hover:text-lambda-900 leading-relaxed</value>
      <webElementGuid>dcb780b4-80fd-41c6-80be-f9b3a1b07608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Radio Buttons Demo</value>
      <webElementGuid>ceeefa66-2828-474b-9f8d-dc6ca7267428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wrapper&quot;]/section[@class=&quot;mb-50&quot;]/div[@class=&quot;container__selenium&quot;]/ul[@class=&quot;list-disc pl-10 pb-30 grid grid-cols-4 w-full gap-10 mt-30 smtablet:grid-cols-1&quot;]/li[@class=&quot;pt-10&quot;]/a[@class=&quot;text-black text-size-14 hover:text-lambda-900 leading-relaxed&quot;]</value>
      <webElementGuid>78289ca1-6259-48a8-b81d-93ef665e6ca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/ul/li[30]/a</value>
      <webElementGuid>76d25499-1468-4206-89b7-0abf9ad44274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Radio Buttons Demo')]</value>
      <webElementGuid>4b4df18a-9950-4f09-8f1b-b3c2b56fc464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progress Bar Modal'])[1]/following::a[1]</value>
      <webElementGuid>b2c2edc8-86a5-4390-839f-9f0c424a62fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overlapped Element'])[1]/following::a[2]</value>
      <webElementGuid>7d8d9b1a-a8db-4414-bd42-c86745653272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redirection'])[1]/preceding::a[1]</value>
      <webElementGuid>04530f51-ad11-41f2-88bb-ccf52c3dc43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Dropdown List'])[1]/preceding::a[2]</value>
      <webElementGuid>9fa9a9b5-39a5-42bc-a97a-8164ea621e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Radio Buttons Demo']/parent::*</value>
      <webElementGuid>a3e06bc7-ec9b-4e99-903a-a392af7e61ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.lambdatest.com/selenium-playground/radiobutton-demo')]</value>
      <webElementGuid>45a7e727-338b-4203-a0e0-3490943201c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[30]/a</value>
      <webElementGuid>38b815af-4c0d-48ee-b509-9d7b7fd5e172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.lambdatest.com/selenium-playground/radiobutton-demo' and (text() = 'Radio Buttons Demo' or . = 'Radio Buttons Demo')]</value>
      <webElementGuid>ecfb0b30-c036-45a3-a7aa-88a4e337a53d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
