<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get value</name>
   <tag></tag>
   <elementGuidId>f5fab096-cf06-41c1-9627-83093851198d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttoncheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttoncheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68550f13-7750-4f1e-a8fc-bc7fbca55fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40cdb21a-e7a2-42e4-b34a-23dd834eff7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttoncheck</value>
      <webElementGuid>c6c96194-02e0-4be8-985c-55eb21b152f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-10 bg-lambda-900 border border-lambda-900 text-white rounded px-15 py-5 hover:bg-transparent hover:text-lambda-900 focus:outline-none</value>
      <webElementGuid>a2b23bfe-9f31-4dd7-80c5-a522146c205e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get value</value>
      <webElementGuid>37c1ed59-8c47-460a-b3a7-00c5f1b5aedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttoncheck&quot;)</value>
      <webElementGuid>f32edf20-46d7-4ba4-b2fb-d1b62f1e41b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttoncheck']</value>
      <webElementGuid>50dcbef7-f448-4eae-aa03-fb437160b0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div/div/button</value>
      <webElementGuid>da85be49-1225-43cd-9a03-4c191da05605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::button[1]</value>
      <webElementGuid>e2d69e60-93c8-4953-9dd3-a58ab2585fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::button[1]</value>
      <webElementGuid>3652caf1-c3c8-4bc3-9797-d8ac56c32173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio Button 1'])[1]/preceding::button[1]</value>
      <webElementGuid>f12ec1c7-f294-4043-b867-e95ce0673c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radio Button 2'])[1]/preceding::button[1]</value>
      <webElementGuid>1cdfd03e-b51b-4370-b896-78e7db06b9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get value']/parent::*</value>
      <webElementGuid>28e05483-da73-4c96-8eb8-37eb13633ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div/button</value>
      <webElementGuid>27d0eff3-8b73-4667-b06b-bc0bf3e2f40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'buttoncheck' and (text() = 'Get value' or . = 'Get value')]</value>
      <webElementGuid>1916247c-bb73-4362-9aea-e6d553498264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
