<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Checked Value</name>
   <tag></tag>
   <elementGuidId>c25b1c95-b63f-4eea-8c1b-feb4fefb487a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='showInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b57633e9-566c-45fa-9d39-21300b258098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cc96b26-8013-49be-a042-00cc69df185b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showInput</value>
      <webElementGuid>6fbf77e6-c77a-4648-9b6e-0ab7cc3220ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-20 mb-10 bg-lambda-900 hover:bg-transparent hover:text-lambda-900 border border-lambda-900 text-white p-10 rounded focus:outline-none w-180</value>
      <webElementGuid>5a70391a-3ed4-46af-8e06-eee362c770de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Checked Value</value>
      <webElementGuid>76a7612f-6f00-4dd6-85bc-83cecc1c6c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showInput&quot;)</value>
      <webElementGuid>8c34d4e9-4379-48b0-a297-bf94e49d0858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='showInput']</value>
      <webElementGuid>6566692e-26df-4db4-9e80-6679b10da251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>b676e597-0bab-4ab5-a04b-7662dc9b5efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Input Field'])[1]/following::button[1]</value>
      <webElementGuid>364944ca-333f-4231-a912-5b279135479a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple Form Demo'])[1]/following::button[1]</value>
      <webElementGuid>ac17e5f5-617b-491e-985d-639fb15abc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message:'])[1]/preceding::button[1]</value>
      <webElementGuid>7d774053-6454-4e0b-80a3-7dce9daeeae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two Input Fields'])[1]/preceding::button[1]</value>
      <webElementGuid>81cf8556-5c2b-443a-bd1b-d59401dcaeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Checked Value']/parent::*</value>
      <webElementGuid>02dd7c6e-f25b-4706-b6b8-5dc06e773b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>6e8ace72-ecf1-4615-9a6d-83d215567cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'showInput' and (text() = 'Get Checked Value' or . = 'Get Checked Value')]</value>
      <webElementGuid>3b14c686-d03c-442d-a71d-d1a2a3971afe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
