<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Option 2_ex1-check3</name>
   <tag></tag>
   <elementGuidId>4d5fd74c-49f2-4f1d-a024-9bb2ad3092f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ex1-check3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ex1-check3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>312eaf3e-e5e5-4f62-8e56-7d18c852851a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fc2961a2-6dc9-42e9-99ae-b9e54e0e456c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cb-element mr-10</value>
      <webElementGuid>804e488b-08f7-4378-a52f-c5b533ab81d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ex1-check3</value>
      <webElementGuid>11e97356-dcd2-4704-a29f-b21c2f2386b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wrapper&quot;]/section[@class=&quot;mt-30&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;smtablet:block&quot;]/div[@class=&quot;w-full px-15&quot;]/div[@class=&quot;mt-50 rounded w-full&quot;]/div[@class=&quot;input-body mt-20&quot;]/div[@class=&quot;w-full rigth-input flex items-center justify-between smtablet:block&quot;]/div[3]/input[@id=&quot;ex1-check3&quot;]</value>
      <webElementGuid>2e2986ab-cea6-4099-bf18-dc0944a41111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ex1-check3']</value>
      <webElementGuid>f08c8374-8e7c-49cf-9ff2-6cf7d98ca296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div[3]/div[2]/div/div[3]/input</value>
      <webElementGuid>d2cf0fe9-2dc7-425c-8576-af88ae65edf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[3]/input</value>
      <webElementGuid>23df03ae-5d7d-47f1-9817-3d909a6b75d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ex1-check3']</value>
      <webElementGuid>499e5c0d-76f9-4e74-a441-754beb271010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
