<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Two Input Fields_sum1</name>
   <tag></tag>
   <elementGuidId>6e1a6a29-fce6-4e2c-97a1-d4b8ae3b4b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sum1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sum1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a68a5559-68af-4200-ab1c-b4b2590dc2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60be8b5e-d817-4076-bfd3-9215682edd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-550 w-full h-35 rounded px-10</value>
      <webElementGuid>83504d6c-3415-4da9-af8d-7511fd060055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter first value</value>
      <webElementGuid>e3740225-5ae4-48f3-a250-c35d36be9362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sum1</value>
      <webElementGuid>eea0e705-9232-4c99-bde1-da4ef7ab522f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sum1&quot;)</value>
      <webElementGuid>24bf1d3e-e2a3-41e5-bf0c-fc94701df1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sum1']</value>
      <webElementGuid>8d47a3de-e5dc-4904-abd3-2007bac3e18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gettotal']/input</value>
      <webElementGuid>bd5adf15-bb6c-47a9-9222-0fdb26b8951a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/input</value>
      <webElementGuid>f3b308bc-d87d-40d7-b179-7f993119d41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Please enter first value' and @id = 'sum1']</value>
      <webElementGuid>28e69fa0-4599-4bcf-88d5-6d8af43d6c64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
