<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_address_line2</name>
   <tag></tag>
   <elementGuidId>c0e36e29-e1ac-4f86-bb02-4fc0de9a4f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAddress2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputAddress2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93f3d0ee-6846-4237-bae9-681d6aaf45d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0476f60b-ab8e-41d1-bf53-2983019e485c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border border-gray-90 text-size-14 rounded mt-10 px-10 py-5</value>
      <webElementGuid>68b45a7d-ec93-4fec-a4f8-f7a815095d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAddress2</value>
      <webElementGuid>3940b757-4981-44ba-93ec-deb1fb31cd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_line2</value>
      <webElementGuid>72f5821e-4820-424a-994b-5da357a85cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 2</value>
      <webElementGuid>e16924ff-621a-4912-bdf6-3d90a3b72615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAddress2&quot;)</value>
      <webElementGuid>621fa11a-442b-497f-8744-19467801d707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAddress2']</value>
      <webElementGuid>5d6f5ddf-8751-4bb0-bfa9-10c8f6ecf596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='seleniumform']/div[4]/div[2]/input</value>
      <webElementGuid>538183ae-2cb3-42d1-9441-6a6c0df7a167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>f98654d7-c01e-41ab-bc24-fa493b9b8540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAddress2' and @name = 'address_line2' and @placeholder = 'Address 2']</value>
      <webElementGuid>0e3e8c0d-c01a-4785-a683-6ed8f1275099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
