<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Option 4_box</name>
   <tag></tag>
   <elementGuidId>a4eb7d1d-60e7-4549-9c07-456d8a36ec91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66881e3c-d69d-4a9f-9e66-aee356039977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17689cfe-038f-4f2f-9404-6e92b62f5dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-10 rounded w-150 box btn bg-lambda-900 selenium_btn bg-black text-white px-10 py-5 cursor-pointer hover:bg-lambda-900</value>
      <webElementGuid>4ea6f706-96a2-499e-b63d-32e86c925879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>333afff5-d8b1-4283-bc06-788a3d39df0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Check All</value>
      <webElementGuid>8605721f-a160-4968-9932-9bd4d3496669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box&quot;)</value>
      <webElementGuid>c1bdee9b-f9c7-4a3d-9cf0-a6cc5f5124b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='box']</value>
      <webElementGuid>a8db727e-9894-4ff6-a603-07d17870653c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>c0ec5f8c-50bf-4331-8d84-1ce69d6aface</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/input</value>
      <webElementGuid>672b7060-5997-426f-bcd8-175bb3d694c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'box']</value>
      <webElementGuid>f3e88c1c-939a-4d88-9a35-bcb7f66f2598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
