<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Disabled Checkbox Demo_mr-10</name>
   <tag></tag>
   <elementGuidId>ed2f9a79-ac0d-44e6-88a1-28cd9871a69d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > input.mr-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c48937c6-5b61-431c-88dc-413865c5668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e3be537e-48d5-4303-bf08-2f2cc2263bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-10</value>
      <webElementGuid>b3bdfdd4-6af0-4773-92ca-e75f6aab8a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wrapper&quot;]/section[@class=&quot;mt-30&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;smtablet:block&quot;]/div[@class=&quot;w-full px-15&quot;]/div[@class=&quot;mt-50 rounded w-full&quot;]/div[@class=&quot;pb-10&quot;]/div[1]/input[@class=&quot;mr-10&quot;]</value>
      <webElementGuid>8a95cfd8-e715-4b0d-bdcb-f1a9266084dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>f2e2c4ee-7220-44b6-858b-d2a54606fd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>33a6debd-ff18-44e7-ad6f-e3a013422b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d777717f-35fe-417a-b892-03332ff2839d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>e7ed508a-fbbe-44f1-8df3-26e0e52e9499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
