<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Two Input Fields_sum2</name>
   <tag></tag>
   <elementGuidId>0b12d159-b0c7-45f2-b9ca-593ad70b9dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sum2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sum2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51d07867-6f9f-448b-b16a-07ccf96757ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a7781fe-0416-4d47-98ae-ee06319aab69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-550 w-full h-35 rounded px-10</value>
      <webElementGuid>ed22da36-0be1-4390-b3e0-683b3a68fc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter second value</value>
      <webElementGuid>c5e51aa5-c4cc-4e42-b24e-20c3f924c3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sum2</value>
      <webElementGuid>f8d9fc7b-0e51-4750-8a36-4dfbbe11b66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sum2&quot;)</value>
      <webElementGuid>ec387b00-413a-4812-8361-98d34eae03ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sum2']</value>
      <webElementGuid>e30259a0-835e-4dfc-9523-1092de79eeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gettotal']/input[2]</value>
      <webElementGuid>346c7093-92f2-4699-b08e-a0f2a6bed6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>9d149c53-cda4-47cf-88ae-4dd18d18a9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Please enter second value' and @id = 'sum2']</value>
      <webElementGuid>02901bdc-9a12-4612-ad6e-e8f6f719798f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
