<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Entered value is not a number</name>
   <tag></tag>
   <elementGuidId>7ea5f29d-1e50-4e84-aba9-b787b4fc63c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='addmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b9543800-1f70-4601-9e89-aab8b783715d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addmessage</value>
      <webElementGuid>951f63e1-bf47-47ca-b2dc-0bdc71f3a15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-20</value>
      <webElementGuid>e7c6db23-9654-4261-8530-b76c0680e629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entered value is not a number</value>
      <webElementGuid>5e6a7cc6-3f9a-41a5-8945-d1732f18e93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addmessage&quot;)</value>
      <webElementGuid>7018d28c-3d04-4744-8f1b-4e6c1a12d6cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='addmessage']</value>
      <webElementGuid>de7dd74d-6ab6-4acd-94f3-8fe5ffb7e59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='user-message']/p)[2]</value>
      <webElementGuid>d40846d6-468c-4171-9341-48578df251c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result:'])[1]/following::p[1]</value>
      <webElementGuid>9b6e54f1-a496-477b-ad22-c131517452f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Sum'])[1]/following::p[1]</value>
      <webElementGuid>1a9b87cc-f8e1-48c8-a13a-ba97bb7e95fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/preceding::p[2]</value>
      <webElementGuid>89151c67-53de-450a-bd12-4d54650a9c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Browser Testing'])[1]/preceding::p[2]</value>
      <webElementGuid>5c2b9b5a-645a-423e-8a5d-f139b6adeca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entered value is not a number']/parent::*</value>
      <webElementGuid>7c5092b4-3e81-4489-a1a8-c50638cec7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/p</value>
      <webElementGuid>fd9e155e-a96d-4b82-b4aa-21f77aecb38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'addmessage' and (text() = 'Entered value is not a number' or . = 'Entered value is not a number')]</value>
      <webElementGuid>e94413d8-c2dd-4026-baa1-73f7bc4bb0a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
