<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>594021b5-0d45-49a2-b8df-042d300ef1b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pickList']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f5df694-5a9e-437b-8fa4-1d2ac43143ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pAdd bg-gray-900 text-white block w-full text-center text-size-14 py-5 mt-15 hover:bg-lambda-900 rounded</value>
      <webElementGuid>a4d7c96e-6d54-4058-8f40-e3630a390f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>ef54d830-811b-4be8-99fc-e3cf67267e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pickList&quot;)/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-2/12 smtablet:w-full pickListButtons pr-20&quot;]/button[@class=&quot;pAdd bg-gray-900 text-white block w-full text-center text-size-14 py-5 mt-15 hover:bg-lambda-900 rounded&quot;]</value>
      <webElementGuid>e432b259-c965-460b-b1ef-15112ec45f34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickList']/div/div[2]/button</value>
      <webElementGuid>e45edfe1-a454-4809-be4c-4cf271a0e233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JQuery Dual List Box'])[1]/following::button[1]</value>
      <webElementGuid>09042581-1cc2-482f-9ce7-c2517c166b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started Free'])[1]/following::button[1]</value>
      <webElementGuid>f26fcdd6-713e-4551-9bfa-b0421f5387bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add All'])[1]/preceding::button[1]</value>
      <webElementGuid>81a9ba12-0448-409e-b2b8-af3d0c8c12cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[2]</value>
      <webElementGuid>200f6110-d777-48a6-ae93-0bcb035ff6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>ed35d46c-c552-432e-ae9a-f381579a1c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>255b6647-8242-45ed-af14-8b376828fa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>64c4c5c1-e0bf-4ae7-b6a0-75acca2fa273</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
