<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Broken Image with AltBroken Image without Alt</name>
   <tag></tag>
   <elementGuidId>52ee5002-d6d8-4859-89ce-6b4828c63cbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.learn_right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section[3]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ac3c2d5-c711-4f25-8405-743d4e29e83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>learn_right</value>
      <webElementGuid>5de06fc0-e577-4738-a10d-2ab7249c7cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Broken Image with AltBroken Image without Alt</value>
      <webElementGuid>c672823f-c22c-49b7-b4ed-340f7976e112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;learn_right&quot;]</value>
      <webElementGuid>c163a37d-002d-4b0a-81fa-bc2993a0b5f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div</value>
      <webElementGuid>1fdf3729-5308-4798-9726-78060316143f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken Images'])[1]/following::div[4]</value>
      <webElementGuid>4e907d95-0ef9-4c3d-aed2-68edc87619d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started Free'])[1]/following::div[6]</value>
      <webElementGuid>82c42e3a-a317-4f90-b2c9-6ce0f94a9632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div</value>
      <webElementGuid>b2a0a23d-f0ff-45b1-a747-40870058d7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Broken Image with AltBroken Image without Alt' or . = 'Broken Image with AltBroken Image without Alt')]</value>
      <webElementGuid>b09156cb-adbb-4215-b71c-e21978dc40cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
