<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drop here_mydropzone</name>
   <tag></tag>
   <elementGuidId>5ee17fc9-3c6f-462c-8e49-9946f444f2b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mydropzone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mydropzone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b0cebc6-83f6-4480-8b1b-4174951218b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mydropzone</value>
      <webElementGuid>dc25c472-4ee6-4c2d-a7f6-615029f15c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropzone</name>
      <type>Main</type>
      <value>move</value>
      <webElementGuid>e2b47dae-a406-4cbb-93db-f6c9757ea135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mydropzone&quot;)</value>
      <webElementGuid>13522b63-bfb9-4637-9511-33ad959ec1d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mydropzone']</value>
      <webElementGuid>fda881dc-41bb-4827-a235-ea1a107413e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>0c254a48-65cc-4dfc-9ed1-b2d9d0188951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>f3aa6f53-2542-41e6-8ad4-ef6cc193a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mydropzone']</value>
      <webElementGuid>3d63f45e-bf19-49f9-aeb1-c58af368d953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
