<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Broken Image with Alt_border border-gra_9f3ca0</name>
   <tag></tag>
   <elementGuidId>ece1feba-963f-44d2-a8e7-f483ee0b7908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.border.border-gray-10.inline-block.w-100.h-100.mt-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section[3]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08eb1888-428b-4d94-ba95-3bd721dca6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-10 inline-block w-100 h-100 mt-10</value>
      <webElementGuid>b83a6ecc-7ee2-4b63-b8a6-0e8613fbfe61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex smtablet:block&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;learn_right&quot;]/div[@class=&quot;border border-gray-10 inline-block w-100 h-100 mt-10&quot;]</value>
      <webElementGuid>9ad0a9d5-d322-4444-9143-907ae92beb9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div/div</value>
      <webElementGuid>e5f18aeb-a6a5-4048-b927-7353d1b93388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken Image with Alt'])[1]/following::div[1]</value>
      <webElementGuid>2d65676c-45d7-41d5-ba35-a5e46a18d356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken Images'])[1]/following::div[5]</value>
      <webElementGuid>848ee8af-4845-40c2-b6de-6f25546fe8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken Image without Alt'])[1]/preceding::div[1]</value>
      <webElementGuid>9c0b3104-d273-491e-9c70-aae5f86226c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/preceding::div[2]</value>
      <webElementGuid>8b77d4c5-91b9-476b-bfb4-73f1da593146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div/div</value>
      <webElementGuid>99cbe949-9041-41c3-b84c-603d115f4f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
