<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data List Filter_input-search</name>
   <tag></tag>
   <elementGuidId>68a16608-e83e-44ab-b4dd-475ddb30d96b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a74dcc1c-691f-49de-b10e-25cb025d769c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c9f90463-4ed8-41ef-b616-17b18476b7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border border-gray-400 rounded px-10 w-full h-35</value>
      <webElementGuid>204092cd-6fe7-4aaa-a92a-2ac3adf7b026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-search</value>
      <webElementGuid>f64ebc36-eeaf-43b1-8cdf-4796d8e25153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Attendees...</value>
      <webElementGuid>bc9c64a9-4615-412d-a92b-1d5769dad555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-search&quot;)</value>
      <webElementGuid>a1216fe2-faf3-48d4-af71-3693609ce3ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-search']</value>
      <webElementGuid>c7c71302-9d3e-4fbd-b1ed-03ada8703d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div/input</value>
      <webElementGuid>6eea2d09-739d-40ed-b97b-89066b073d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>68989bb3-3157-4bc6-a3c8-e5456ec0205e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-search' and @placeholder = 'Search Attendees...']</value>
      <webElementGuid>1207410c-e4b6-4259-a029-164085cba1a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
