<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Data List Filter_input-search</name>
   <tag></tag>
   <elementGuidId>68a16608-e83e-44ab-b4dd-475ddb30d96b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e98a2acd-0d2a-4ad6-aee6-eb87a241680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ca474bc1-6726-4b96-8232-b9a7599369be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border border-gray-400 rounded px-10 w-full h-35</value>
      <webElementGuid>69d9fd6b-4bea-49cd-9709-75f95161a091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-search</value>
      <webElementGuid>974f6358-5984-44df-9185-a7b8fb1faf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Attendees...</value>
      <webElementGuid>96dc3cbf-cc97-4d1e-b1dc-054bba10b29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-search&quot;)</value>
      <webElementGuid>d5146cab-6093-481a-b224-0d823dd333ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-search']</value>
      <webElementGuid>f624beca-fa79-4423-be55-2e270e8aae70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[3]/div/div/div/div/input</value>
      <webElementGuid>588f098e-0150-42d2-a742-93548c2a1e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>e2e962e1-bd2c-49fa-858f-aa3489ee886d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-search' and @placeholder = 'Search Attendees...']</value>
      <webElementGuid>d7b136a7-0107-4735-915e-53ee7acb94e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
