<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Click Me</name>
   <tag></tag>
   <elementGuidId>c4270c49-4a7d-47c9-997d-42918b6a2154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UgZnG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='UgZnG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5169d044-ff36-45c8-9449-026cc4b18917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UgZnG</value>
      <webElementGuid>cd9e981c-0fba-471b-86b2-c5223f494389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33f0353a-1d2c-43e0-bd72-5d39e5fe4164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c1b14e52-bcd5-46dd-b059-7e8f6e692ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click Me</value>
      <webElementGuid>2afc1557-929a-4b1b-b732-2394e9315b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UgZnG&quot;)</value>
      <webElementGuid>4c1e77b9-33fb-43e5-a036-ce51f8c71b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='UgZnG']</value>
      <webElementGuid>24b67047-179a-42ee-920b-c154adeeb3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[3]/button</value>
      <webElementGuid>253d5def-0cbb-4aa9-88e0-59c533799673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right Click Me'])[1]/following::button[1]</value>
      <webElementGuid>2982792b-d867-4294-892a-50a20e33a246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Click Me'])[1]/following::button[2]</value>
      <webElementGuid>43561279-20a6-4953-a064-af35a7fa94c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::button[1]</value>
      <webElementGuid>d6ea7354-a014-4841-bc1c-f790d4eddea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'UgZnG', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>bb8cfd75-1578-472a-85ea-691f0df5708f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click Me']/parent::*</value>
      <webElementGuid>1b017043-02e8-4a05-a141-0ca34a41bfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>74705e42-ce34-49f9-857a-3e91b44b748f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'UgZnG' and @type = 'button' and (text() = 'Click Me' or . = 'Click Me')]</value>
      <webElementGuid>153799bb-210a-405c-98da-54f4b90446fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Ua579']</value>
      <webElementGuid>675134bf-9e33-4ec2-b020-1daf3af16fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'Ua579', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>30a84a57-dbc5-4aab-87c0-59ba4f5e7734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Ua579' and @type = 'button' and (text() = 'Click Me' or . = 'Click Me')]</value>
      <webElementGuid>08013a6a-e0bf-4cf2-ab24-10de48da7690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sJyeR']</value>
      <webElementGuid>a37031aa-189b-4e2f-9af9-ed1da7542aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'sJyeR', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>c69f6ecc-fec1-47a1-911c-f6ab680c4812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sJyeR' and @type = 'button' and (text() = 'Click Me' or . = 'Click Me')]</value>
      <webElementGuid>c0b099f5-6b52-44cc-be09-007448478aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
