<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Where does it come from</name>
   <tag></tag>
   <elementGuidId>94872ad7-9a34-4950-9931-3036e8b0ff72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#section2Heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section2Heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>151755bb-04be-4b4f-b759-92d5291c9d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>81e03707-b81e-44ba-a052-2a438eaf22ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>section2Heading</value>
      <webElementGuid>46a055e8-3a81-4501-b6f3-ba06e2d28d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Where does it come from?</value>
      <webElementGuid>409f0b23-95a3-4fd5-bb5d-485767c2d4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section2Heading&quot;)</value>
      <webElementGuid>1a96704b-1ec6-4480-8873-55aad4ed2072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='section2Heading']</value>
      <webElementGuid>690dbff8-d933-4db4-8e9b-1772735c42c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordianContainer']/div/div[2]/div</value>
      <webElementGuid>1d684c5b-3449-435b-9e7b-1d392ddee54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Lorem Ipsum?'])[1]/following::div[4]</value>
      <webElementGuid>b30081ea-edc5-4c8d-b62c-e909f76d775c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[11]</value>
      <webElementGuid>5b46d131-417d-4b45-9c6f-cb1dfee2bec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why do we use it?'])[1]/preceding::div[3]</value>
      <webElementGuid>1b9e6e7c-3569-4285-8ad5-6f623ac3141d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[14]</value>
      <webElementGuid>29bc39f8-8af8-4d9c-a14c-56885f7fdc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Where does it come from?']/parent::*</value>
      <webElementGuid>8cb1231a-ce3e-46f9-aee6-f1fda4a3fcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>59f8f409-11b1-4481-83cf-f167228103a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'section2Heading' and (text() = 'Where does it come from?' or . = 'Where does it come from?')]</value>
      <webElementGuid>a6c0a320-ba09-4797-8680-620c85b9b8a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
