<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Web Tables_adplus-anchor</name>
   <tag></tag>
   <elementGuidId>93d1155b-ca3e-4f1b-bdad-81b2b571bd15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adplus-anchor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adplus-anchor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72173f07-50ac-41b6-8851-5bd65d2973b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adplus-anchor</value>
      <webElementGuid>fad210cc-6a95-462b-bf24-bc6f86d51957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-query-id</name>
      <type>Main</type>
      <value>CJrsuLOhloIDFa2GrAIdA3QOlA</value>
      <webElementGuid>54292a45-1a7b-49dd-b780-9c5ce152fc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adplus-anchor&quot;)</value>
      <webElementGuid>48525d99-a7b8-4d1c-ba77-03773f7cabae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='adplus-anchor']</value>
      <webElementGuid>38e8bff4-b9a7-4914-8d9e-614a791467f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fixedban']/div/div[2]</value>
      <webElementGuid>4462bb8e-6062-4a01-a27f-a711f68a80f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Tables'])[1]/preceding::div[2]</value>
      <webElementGuid>3ca4a27c-52d9-4e3f-a950-ec1080f4e3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elements'])[1]/preceding::div[4]</value>
      <webElementGuid>6d836b52-43cb-4cf3-8d47-26c8c760fca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>18700215-64cc-49dd-b3eb-a8c9fadc2f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'adplus-anchor']</value>
      <webElementGuid>e308acce-095b-4a07-9ab0-d4fa5661fb4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
