<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Doodles Archive_logo</name>
   <tag></tag>
   <elementGuidId>f35a24de-b114-43e3-a0c6-99a13e2de755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9aa36787-f205-4698-bc83-1e2f177435e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/doodles</value>
      <webElementGuid>e8b1c1cb-bafe-4e0e-91b6-7180206c82d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>f3db298e-c681-4be1-8ec1-c1c6229da497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Google Doodles</value>
      <webElementGuid>e1ee240e-4cb9-4ba0-9228-95db6695ae3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)</value>
      <webElementGuid>b26f6243-2e97-431a-ba21-eb9d95488458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logo']</value>
      <webElementGuid>48e5104f-8b76-4678-915f-3e503e575523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-wrap']/a</value>
      <webElementGuid>20a71f47-8653-4635-9a45-b0af1a69a7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/doodles')]</value>
      <webElementGuid>782a3fa9-8816-4f1d-b15e-cd01204c273d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>09284f27-74cc-4cc1-8daf-68a38ca96dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/doodles' and @id = 'logo' and @title = 'Google Doodles']</value>
      <webElementGuid>19bc4b1a-eb3d-48c5-b8c1-c2d9309d47f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
